### ISSUE TITLE
Installing...

### ISSUE THREAD

**Issue by Gabrielabp** [tavareshugo/WindowScanR#5]
Any idea how to solve this one?
Error: package or namespace load failed for ‘windowscanr’ in get(Info[i, 1], envir = env):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/dplyr/R/dplyr.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

**Comment by tavareshugo** [comment]
@Gabrielabp I think that might be a problem with your `dplyr` package installation. I would suggest to restart R and reinstall `dplyr` to the latest version. Also, check if you can load that package `library(dplyr)` or if you get the same error.

**Comment by tavareshugo** [comment]
Closing as no further comments from user.
